### ISSUE TITLE
Bug: Text does not align if a name appears at the very start of a document

### ISSUE THREAD

**Issue by dimus** [gnames/gntagger#32]
[termit.txt](https://github.com/gnames/gntagger/files/1458309/termit.txt)
![screenshot from 2017-11-09 10-16-50](https://user-images.githubusercontent.com/12124/32616119-2b0c1474-c537-11e7-9512-ea45af1ac037.png)

**Comment by alexander-myltsev** [comment]
This is duplicate of: https://github.com/gnames/gntagger/issues/32
