### ISSUE TITLE
As a User I want to see stats during curation

### ISSUE THREAD

**Issue by dimus** [gnames/gntagger#6]

**Comment by mjy** [comment]
I'd say be careful here- don't overload the interface to distract from the core purpose of making yes/no/maybe decisions.   Maybe you need a companion web-service app dashboard that does this, can be running in the background.

**Comment by dimus** [comment]
I agree, it is important not to add stats just for the sake of it, but a few of them will be important. For example, when we have an ability to add false negatives, the threshold of where we cut 'no name/possible false negative' would be very helpful to display. And no plots, just numbers :)

**Comment by dimus** [comment]
![6-ticket](https://user-images.githubusercontent.com/12124/32629784-fbf58f0c-c55f-11e7-89f3-ac8847ca09b8.png)

**Comment by dimus** [comment]
Recall and `Added` would not work until we get odds for each name

Colors for stats 

`Accepted` - green

`Rejected`  - red

`Modified`  - magenta

`Added`    -  yellow?

The last percentage is a progress from the furthest point

**Comment by alexander-myltsev** [comment]
`Precision = count(!NotName) / total_found_names`

Recall -- don't estimate
`Added` -- don't estimate
Drop progress text

**Comment by dimus** [comment]
When I move 4 names forward and mark one name as "NotName" the resulting stats are not Acc. 75% Rej.25%, but Acc. 30%, Rej. 70%. Also by some reason Recall and Add are becoming negative (-1)
![screenshot from 2017-11-15 11-02-04](https://user-images.githubusercontent.com/12124/32849458-d0ebc5c6-c9f4-11e7-86a6-a9533524f6b8.png)

**Comment by alexander-myltsev** [comment]
That most probably means that `Cephalapoda` occurs in rest words. And those are automatically assigned to `NotName`, that affects stats.

`-1` means that `gntagger` doesn't estimate it yet. Just let me know what value to put instead.

**Comment by dimus** [comment]
lets count data only up to the furthest advancement of a cursor, as everything beyond it is not yet seen and approved.

**Comment by dimus** [comment]
I think the best is to change -1 to "n/a" for both Recall and Add, keeping the 'right' amount of empty spaces to compensate for future numbers.

Precision stays 0.00 after I went through 443 name candidates with 98% accepted

I wonder if we can normalize Acc, Rej, Mod, Add stats so that they always give 100% as a sum. May be just showing one decimal will suffice. We do have space so far for that. (On the picture we have 
98 0 0 now)

![screenshot from 2017-11-16 04-48-32](https://user-images.githubusercontent.com/12124/32887426-7b8b4df0-ca89-11e7-8688-0dbb8d9eb4a7.png)
